In [1]:
import numpy as np
import torch
from torch import nn, Tensor
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor, Lambda, Compose

In [69]:
A = Tensor([[0, 1], [3, 4]])
B = Tensor([[6, 7], [8, 9]])

In [70]:
A.requires_grad = True
B.requires_grad = True

In [71]:
C = torch.matmul(A, B)

In [73]:
C.backward(Tensor([[1, 0], [0, 1]]))

In [74]:
A.grad

tensor([[6., 8.],
        [7., 9.]])

In [75]:
B.grad

tensor([[0., 3.],
        [1., 4.]])

In [76]:
A.T

tensor([[0., 3.],
        [1., 4.]], grad_fn=<PermuteBackward0>)

In [77]:
B.T

tensor([[6., 8.],
        [7., 9.]], grad_fn=<PermuteBackward0>)

In [4]:
A = np.array([[-1, 5], [-1, 5]])
B = np.array([[0, 0], [0, 0]])

In [24]:
mask_a = A > B
mask_b = B > A

In [25]:
grad = np.array([[1, 2], [3, 4]])

In [28]:
mask_b

array([[ True, False],
       [ True, False]])

In [26]:
np.multiply(mask_a, grad)

array([[0, 2],
       [0, 4]])

In [29]:
np.multiply(mask_b, grad)

array([[1, 0],
       [3, 0]])

In [30]:
np.maximum(A, B)

array([[0, 5],
       [0, 5]])

In [31]:
np.zeros_like(grad)

array([[0, 0],
       [0, 0]])

In [2]:
x = np.array([1, 2, 3])
g = 1.0 / (1.0 + np.exp(-x))

In [3]:
g

array([0.73105858, 0.88079708, 0.95257413])

In [6]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[1, 2], [3, 4]])

In [7]:
A

array([[1, 2],
       [3, 4]])

In [8]:
B

array([[1, 2],
       [3, 4]])

AttributeError: 'numpy.ndarray' object has no attribute 'multiply'